CREATE DEFINER = CURRENT_USER TRIGGER `mydb`.`Sumario_BEFORE_INSERT` BEFORE INSERT ON mdyb.sumario FOR EACH ROW
BEGIN
	SET @X = (select COUNT(*) From DESIGNACION DES INNER JOIN OFICIAL OFI ON DES.NUM = OFI.NUM WHERE DES.IDDESIGNACION = NEW.IDDESIGNACION and des.num = new.oficialqueinvestiga);    
    IF @X > 0
    THEN
              SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'UN OFICIAL NO PUEDE INVESTIGARSE A SI MISMO';
    END IF;
END;

